### ISSUE TITLE
HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 140669461211008:-----my HDF5 is 2.0

### ISSUE THREAD

**Issue by SeekPoint** [XingxingZhang/td-treelstm#1]
envy@ub1404:~/os_pri/github/td-treelstm/scripts$ bash run_msr.sh 
{
  bidirectional : false
  test : "/media/envy/data1t/dataset/raw/msr.dep.100.test"
  ignoreCase : true
  batchSize : 64
  sort : 20
  train : "/media/envy/data1t/dataset/raw/msr.dep.100.train"
  dataset : "/media/envy/data1t/dataset/raw/savedisk/msr.dep.100.h5"
  valid : "/media/envy/data1t/dataset/raw/msr.dep.100.valid"
  freq : 5
  keepFreq : true
  maxLen : 100
}
totally 2210370 lines
freqs size 65346
original #words 218561, after cut = 5, #words 65346
word2idx -- table  
UNK -- 1  
keepFreq -- true  
freqs -- table  
freqCut -- 5  
nvocab -- 65346 
uniqUNK -- 153216  
idx2word -- table  
ignoreCase -- true  
UNK_TOKEN -- ###unk###  
save vocab to /media/envy/data1t/dataset/raw/savedisk/msr.dep.100.vocab.t7
[deptree2hdf5] line count = 50000
[deptree2hdf5] line count = 100000
[deptree2hdf5] line count = 150000
[deptree2hdf5] line count = 200000
[deptree2hdf5] line count = 250000
[deptree2hdf5] line count = 300000
[deptree2hdf5] line count = 350000
[deptree2hdf5] line count = 400000
[deptree2hdf5] line count = 450000
[deptree2hdf5] line count = 500000
[deptree2hdf5] line count = 550000
[deptree2hdf5] line count = 600000
[deptree2hdf5] line count = 650000
[deptree2hdf5] line count = 700000
[deptree2hdf5] line count = 750000
[deptree2hdf5] line count = 800000
[deptree2hdf5] line count = 850000
[deptree2hdf5] line count = 900000
[deptree2hdf5] line count = 950000
[deptree2hdf5] line count = 1000000
[deptree2hdf5] line count = 1050000
[deptree2hdf5] line count = 1100000
[deptree2hdf5] line count = 1150000
[deptree2hdf5] line count = 1200000
[deptree2hdf5] line count = 1250000
[deptree2hdf5] line count = 1300000
[deptree2hdf5] line count = 1350000
[deptree2hdf5] line count = 1400000
[deptree2hdf5] line count = 1450000
[deptree2hdf5] line count = 1500000
[deptree2hdf5] line count = 1550000
[deptree2hdf5] line count = 1600000
[deptree2hdf5] line count = 1650000
[deptree2hdf5] line count = 1700000
[deptree2hdf5] line count = 1750000
[deptree2hdf5] line count = 1800000
[deptree2hdf5] line count = 1850000
[deptree2hdf5] line count = 1900000
[deptree2hdf5] line count = 1950000
[deptree2hdf5] line count = 2000000
[deptree2hdf5] line count = 2050000
[deptree2hdf5] line count = 2100000
[deptree2hdf5] line count = 2150000
[deptree2hdf5] line count = 2200000
[train] delete 0 sentences
[train] totally 2210370 lines
create training set done!  
[valid] delete 0 sentences
[valid] totally 4000 lines
create validating set done! 
[test] delete 0 sentences
[test] totally 1040 lines
create testing set done!  
save dataset to /media/envy/data1t/dataset/raw/savedisk/msr.dep.100.h5
{
  bidirectional : false
  test : "/media/envy/data1t/dataset/raw/msr.dep.100.test"
  ignoreCase : true
  batchSize : 64
  sort : 20
  train : "/media/envy/data1t/dataset/raw/msr.dep.100.train"
  dataset : "/media/envy/data1t/dataset/raw/savedisk/msr.dep.100.h5"
  valid : "/media/envy/data1t/dataset/raw/msr.dep.100.valid"
  freq : 5
  keepFreq : true
  maxLen : 100
}
========begin to sort dataset========  
cp /media/envy/data1t/dataset/raw/savedisk/msr.dep.100.vocab.t7 /media/envy/data1t/dataset/raw/savedisk/msr.dep.100.sort20.vocab.t7 
HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 140669461211008:
  #000: ../../../src/H5Dio.c line 182 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: ../../../src/H5Dio.c line 550 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: ../../../src/H5Dchunk.c line 1837 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: ../../../src/H5Dchunk.c line 2954 in H5D__chunk_lock(): unable to preempt chunk(s) from cache
    major: Low-level I/O
    minor: Unable to initialize object
  #004: ../../../src/H5Dchunk.c line 2740 in H5D__chunk_cache_prune(): unable to preempt one or more raw data cache entry
    major: Low-level I/O
    minor: Unable to flush data from cache
  #005: ../../../src/H5Dchunk.c line 2607 in H5D__chunk_cache_evict(): cannot flush indexed storage buffer
    major: Low-level I/O
    minor: Write failed
  #006: ../../../src/H5Dchunk.c line 2526 in H5D__chunk_flush_entry(): unable to insert/resize chunk
    major: Dataset
    minor: Unable to insert object
  #007: ../../../src/H5Dbtree.c line 959 in H5D__btree_idx_insert(): unable to allocate chunk
    major: Low-level I/O
    minor: Write failed
  #008: ../../../src/H5B.c line 605 in H5B_insert(): unable to locate root of B-tree
    major: B-Tree node
    minor: Unable to protect metadata
  #009: ../../../src/H5AC.c line 1278 in H5AC_protect(): no write intent on file
    major: Object cache
    minor: Bad value
/home/envy/torch/install/bin/luajit: /home/envy/torch/install/share/lua/5.1/hdf5/dataset.lua:160: HDF5DataSet:partial() - failed reading data from [HDF5DataSet (83886213 /train/index DATASET)]
stack traceback:
    [C]: in function 'assert'
    /home/envy/torch/install/share/lua/5.1/hdf5/dataset.lua:160: in function 'partial'
    ./sorthdf5.lua:56: in function 'getLengths'
    ./sorthdf5.lua:21: in function 'sortHDF5'
    deptree2hdf5.lua:84: in function 'sort'
    deptree2hdf5.lua:92: in main chunk
    [C]: in function 'dofile'
    ...envy/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670
HDF5: infinite loop closing library
      D,G,S,T,D,G,S,F,D,S,F,FD,P,FD,P,FD,P,E,E,SL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL
envy@ub1404:~/os_pri/github/td-treelstm/scripts$ 
envy@ub1404:~/os_pri/github/td-treelstm/scripts$ 
envy@ub1404:~/os_pri/github/td-treelstm/scripts$ 
envy@ub1404:~/os_pri/github/td-treelstm/scripts$ 
envy@ub1404:~/os_pri/github/td-treelstm/scripts$ git remote -v
origin  https://github.com/XingxingZhang/td-treelstm.git (fetch)
origin  https://github.com/XingxingZhang/td-treelstm.git (push)
envy@ub1404:~/os_pri/github/td-treelstm/scripts$

**Comment by XingxingZhang** [comment]
you can ignore the error and then run

```
# change dataset=... to  dataset=/media/envy/data1t/dataset/raw/savedisk/msr.dep.100.h5 
./run_msr_sort.sh
```

I don't know the reason for the error yet, but I know it always happen when I try to sort a large hdf5 file.

**Comment by SeekPoint** [comment]
./run_msr_sort.sh

got the same error too
